language: node_js
node_js:
  - '0.10'
env:
  global:
    - SAUCE_USERNAME: 
    - SAUCE_ACCESS_KEY: 
before_script:
  - npm install -g bower grunt-cli
  - npm install
  - bower install
script: grunt intern
